<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net472;net6.0;net8.0</TargetFrameworks>
        <Description>Extensions and utilities for working with MassTransit.</Description>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cogito.DependencyInjection" Version="1.0.0" />
        <PackageReference Include="MassTransit" Version="8.5.10" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    </ItemGroup>

</Project>
