<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="TestConsumer1.cs" />
      <Compile Remove="TestConsumer2.cs" />
      <Compile Remove="TestSaga.cs" />
      <Compile Remove="TestSagaMessage.cs" />
      <Compile Remove="TestSagaRequest.cs" />
      <Compile Remove="TestSagaRequestState.cs" />
      <Compile Remove="TestSagaResponse.cs" />
      <Compile Remove="TestSagaState.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Cogito.Components" Version="2.0.5" />
        <PackageReference Include="Cogito.Extensions.Configuration.Autofac" Version="4.0.3" />
        <PackageReference Include="Cogito.Extensions.Logging.Serilog.Autofac" Version="3.0.3" />
        <PackageReference Include="Cogito.Extensions.Options.Configuration.Autofac" Version="4.0.3" />
        <PackageReference Include="Cogito.Autofac" Version="6.1.3" />
        <PackageReference Include="MassTransit" Version="8.5.10" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        
    </ItemGroup>

</Project>
